packages:
  - "apps/*"
  - "packages/*"

catalogs:
  react:
    react: ^19.2.0
    react-dom: ^19.2.0
    "@types/react": ^19.1.0
    "@types/react-dom": ^19.1.0
  tools:
    vite: ^7.1.9
    vitest: ^3.2.4
    eslint: ^9.37.0
    typescript: ^5.9.0
